name: Deploy Angular Frontend to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies and Build
        working-directory: app-frontend
        run: |
          npm install
          npm run build --production

      # - name: Run Tests
      #   working-directory: app-frontend
      #   run: npm run test:ci

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: app-frontend/dist/app-frontend/browser
