name: Deploy Backend API to Render

on:
  workflow_dispatch:

jobs:
  build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies and Build
        working-directory: app-backend
        run: |
          npm install
          npm run build

      # - name: Run Tests
      #   working-directory: app-backend
      #   run: npm test

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Deploy Hook on Render
        env:
          RENDER_DEPLOY_BACKEND_HOOK: ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK }}
        run: curl -X POST "$RENDER_DEPLOY_BACKEND_HOOK"
